"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import Link from "next/link";
import {ArrowLeft,CloudSun,Expand,KeyRound,LogOut,Monitor,PenLine,RefreshCw,RotateCcw,Save,UserRound} from "lucide-react";
import {createClient} from "@/lib/supabase/client";
import {getPirassunungaWeather,type CurrentWeather} from "@/lib/weather";
type Slot={id:string;slot_number:number;status:string};type Audit={disposition:string;reason_code:string;audit_note:string;decided_at:string};type Ev={id:string;key_slot_id:string;event_type:string;holder_name:string;mission:string|null;occurred_at:string;audit:Audit|Audit[]|null};type DutyRosterRow={profiles:{full_name:string;rank:string|null}|null};
function today(){const p=new Intl.DateTimeFormat("en-CA",{timeZone:"America/Sao_Paulo",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date()),v=(t:Intl.DateTimeFormatPartTypes)=>p.find(x=>x.type===t)?.value??"";return`${v("year")}-${v("month")}-${v("day")}`}

export default function Claviculario(){
 const[slots,setSlots]=useState<Slot[]>([]),[events,setEvents]=useState<Ev[]>([]),[selected,setSelected]=useState<Slot|null>(null),[monitor,setMonitor]=useState(false),[mission,setMission]=useState(""),[destination,setDestination]=useState(""),[external,setExternal]=useState(""),[message,setMessage]=useState(""),[saving,setSaving]=useState(false),[hasSignature,setHasSignature]=useState(false),[realtime,setRealtime]=useState("Conectando...");
 const[dutySergeant,setDutySergeant]=useState("carregando..."),[weather,setWeather]=useState<CurrentWeather|null>(null),[weatherStatus,setWeatherStatus]=useState<"loading"|"ready"|"error">("loading");
 const canvas=useRef<HTMLCanvasElement>(null),drawing=useRef(false),lastPoint=useRef<{x:number;y:number}|null>(null);
 const load=useCallback(async()=>{const supabase=createClient();const[s,e]=await Promise.all([supabase.from("key_slots").select("id,slot_number,status").eq("active",true).order("slot_number"),supabase.from("key_events").select("id,key_slot_id,event_type,holder_name,mission,occurred_at,audit:key_event_audits(disposition,reason_code,audit_note,decided_at)").order("occurred_at",{ascending:false}).limit(200)]);if(s.error||e.error){setMessage("Não foi possível atualizar o claviculário.");return}setSlots(s.data??[]);setEvents((e.data??[]) as unknown as Ev[])},[]);
 useEffect(()=>{const supabase=createClient();queueMicrotask(()=>void load());const channel=supabase.channel("keys").on("postgres_changes",{event:"*",schema:"public",table:"key_events"},()=>void load()).on("postgres_changes",{event:"*",schema:"public",table:"key_slots"},()=>void load()).subscribe(status=>{if(status==="SUBSCRIBED"){setRealtime("Tempo real ativo");void load()}else if(status==="CHANNEL_ERROR"||status==="TIMED_OUT"){setRealtime("Reconectando...");void load()}});const fallback=window.setInterval(()=>void load(),30000);return()=>{window.clearInterval(fallback);void supabase.removeChannel(channel)}},[load]);
 useEffect(()=>{const supabase=createClient(),d=today();const loadDuty=async()=>{const{data,error}=await supabase.from("duty_rosters").select("profiles!duty_rosters_profile_id_fkey(full_name,rank)").eq("duty_date",d).maybeSingle();if(error){setDutySergeant("indisponível");return}const p=(data as DutyRosterRow|null)?.profiles;setDutySergeant(p?[p.rank,p.full_name].filter(Boolean).join(" "):"não definido")};void loadDuty();const c=supabase.channel(`duty-${d}`).on("postgres_changes",{event:"*",schema:"public",table:"duty_rosters",filter:`duty_date=eq.${d}`},()=>void loadDuty()).subscribe(status=>{if(status==="SUBSCRIBED")void loadDuty()});return()=>{void supabase.removeChannel(c)}},[]);
 useEffect(()=>{let active=true;const run=async()=>{try{const current=await getPirassunungaWeather();if(active){setWeather(current);setWeatherStatus("ready")}}catch{if(active)setWeatherStatus("error")}};void run();const timer=window.setInterval(()=>void run(),20*60*1000);return()=>{active=false;window.clearInterval(timer)}},[]);
 const auditOf=(event:Ev)=>Array.isArray(event.audit)?event.audit[0]??null:event.audit,annulledEvents=events.filter(event=>auditOf(event)?.disposition==="annulled");
 const latest=(id:string)=>events.find(e=>e.key_slot_id===id),out=(slot:Slot)=>slot.status==="checked_out";
 function clearSignature(){canvas.current?.getContext("2d")?.clearRect(0,0,700,220);setHasSignature(false);drawing.current=false;lastPoint.current=null}
 function resetModal(){setSelected(null);setMission("");setDestination("");setExternal("");setMessage("");setSaving(false);clearSignature()}
 function open(slot:Slot){resetModal();setSelected(slot)}
 function pos(e:React.PointerEvent<HTMLCanvasElement>){const c=canvas.current!,r=c.getBoundingClientRect();return{x:(e.clientX-r.left)*c.width/r.width,y:(e.clientY-r.top)*c.height/r.height}}
 function start(e:React.PointerEvent<HTMLCanvasElement>){drawing.current=true;const p=pos(e),ctx=canvas.current!.getContext("2d")!;lastPoint.current=p;ctx.beginPath();ctx.moveTo(p.x,p.y);canvas.current!.setPointerCapture(e.pointerId)}
 function draw(e:React.PointerEvent<HTMLCanvasElement>){if(!drawing.current)return;const p=pos(e),previous=lastPoint.current,ctx=canvas.current!.getContext("2d")!;if(previous&&Math.hypot(p.x-previous.x,p.y-previous.y)>=1)setHasSignature(true);lastPoint.current=p;ctx.lineWidth=3;ctx.lineCap="round";ctx.strokeStyle="#071f3c";ctx.lineTo(p.x,p.y);ctx.stroke()}
 function stop(){drawing.current=false;lastPoint.current=null}
 async function fullscreen(){setMessage("");try{if(document.fullscreenElement)await document.exitFullscreen();else if(document.documentElement.requestFullscreen)await document.documentElement.requestFullscreen();else throw new Error("recurso indisponível")}catch{setMessage("Não foi possível alterar a tela cheia neste navegador.")}}
 async function logout(){const{error}=await createClient().auth.signOut();if(error){setMessage(`Não foi possível sair: ${error.message}`);return}window.location.href="/login"}
 async function save(){if(!selected||!mission.trim()){setMessage("Informe a missão.");return}if(!hasSignature){setMessage("Faça a assinatura antes de salvar.");return}setSaving(true);const supabase=createClient();const{data:{user}}=await supabase.auth.getUser();if(!user){setMessage("Sessão expirada.");setSaving(false);return}const blob=await new Promise<Blob|null>(resolve=>canvas.current?.toBlob(resolve,"image/webp",.55));if(!blob){setMessage("Não foi possível gerar a assinatura.");setSaving(false);return}const buffer=await blob.arrayBuffer(),hash=Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",buffer))).map(b=>b.toString(16).padStart(2,"0")).join(""),clientId=crypto.randomUUID(),path=`${user.id}/${new Date().toISOString().slice(0,10)}/${clientId}.webp`;const up=await supabase.storage.from("key-signatures").upload(path,blob,{contentType:"image/webp"});if(up.error){setMessage("Erro ao salvar assinatura.");setSaving(false);return}const type=out(selected)?"return":"checkout";const{error}=await supabase.rpc("record_key_event",{p_key_slot_id:selected.id,p_event_type:type,p_mission:mission,p_destination:destination||null,p_notes:external?`Viatura externa: ${external}`:null,p_signature_path:path,p_signature_sha256:hash,p_client_event_id:clientId});if(error){await supabase.storage.from("key-signatures").remove([path]);setMessage(error.message);setSaving(false);return}resetModal();await load()}
 return <main className={monitor?"key-page monitor-mode":"key-page"}><header className="key-header"><div className="key-brand"><Link href="/" aria-label="Voltar ao painel"><ArrowLeft/></Link><img src="/ssv-logo-transparent.png" alt="SSV"/><span><b>Claviculário Digital</b><small>Retirada e devolução de chaves</small></span></div><div className="key-context"><span><UserRound/><small>Sargento de Dia</small><b>{dutySergeant}</b></span><span><CloudSun/><small>Pirassununga</small><b>{weatherStatus==="loading"?"Carregando clima...":weatherStatus==="error"||!weather?"Clima indisponível":`${Math.round(weather.temperatureCelsius)} °C · ${weather.description}`}</b></span></div><div className="key-actions"><button onClick={()=>void load()}><RefreshCw/>Atualizar</button><button onClick={()=>setMonitor(v=>!v)}><Monitor/>Monitor</button><button onClick={()=>void fullscreen()}><Expand/>Tela cheia</button><button onClick={()=>void logout()}><LogOut/>Sair</button></div></header>
  <div className="key-status"><span>{realtime}</span>{message&&!selected&&<p role="alert">{message}</p>}</div><section className="key-summary"><div><b>{slots.length}</b><small>Posições</small></div><div><b>{slots.filter(s=>!out(s)).length}</b><small>Disponíveis</small></div><div><b>{slots.filter(out).length}</b><small>Retiradas</small></div></section><section className="key-grid">{slots.map(s=>{const e=latest(s.id),busy=out(s);return <button key={s.id} className={busy?"key-slot busy":"key-slot"} onClick={()=>!monitor&&open(s)} disabled={monitor}><strong>{s.slot_number}</strong><KeyRound/><b>{busy?"RETIRADA":"DISPONÍVEL"}</b>{e&&<><small>{e.holder_name}</small><em>{e.mission||"Sem missão"}</em><time>{new Date(e.occurred_at).toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"})}</time></>}</button>})}</section>{annulledEvents.length>0&&<section className="key-audit"><div><small>AUDITORIA · SOMENTE ADM MESTRE</small><h2>Eventos anulados preservados</h2><p>Estes registros continuam no histórico e não alteram o estado atual das posições.</p></div><div className="key-audit-list">{annulledEvents.map(event=>{const audit=auditOf(event),slot=slots.find(item=>item.id===event.key_slot_id);return <article key={event.id}><header><strong>Posição {slot?.slot_number??"—"}</strong><b>ANULADO</b></header><span>{event.event_type==="checkout"?"Retirada":"Devolução"} · {event.holder_name}</span><time>{new Date(event.occurred_at).toLocaleString("pt-BR")}</time><p>{audit?.audit_note}</p></article>})}</div></section>}
  {selected&&<div className="key-modal-bg" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)resetModal()}}><section className="key-modal" role="dialog" aria-modal="true" aria-labelledby="key-modal-title"><div className="key-modal-scroll"><div className="key-modal-title"><strong>{selected.slot_number}</strong><div><small>{out(selected)?"DEVOLUÇÃO":"RETIRADA"}</small><h2 id="key-modal-title">Posição {selected.slot_number}</h2></div></div><label>Viatura externa/temporária<input value={external} onChange={e=>setExternal(e.target.value)} placeholder="Ex.: Prefeitura — 10DP174"/></label><label>Missão<input value={mission} onChange={e=>setMission(e.target.value)} required autoFocus/></label><label>Destino<input value={destination} onChange={e=>setDestination(e.target.value)}/></label><div className="signature-label"><span><PenLine/>Assine com o dedo</span><canvas aria-label="Área para assinatura" ref={canvas} width="700" height="220" onPointerDown={start} onPointerMove={draw} onPointerUp={stop} onPointerCancel={stop}/><button type="button" aria-label="Limpar assinatura" onClick={clearSignature}><RotateCcw/>Limpar</button></div>{message&&<p role="alert">{message}</p>}</div><div className="key-modal-actions"><button onClick={resetModal}>Cancelar</button><button className="key-save" onClick={()=>void save()} disabled={saving||!hasSignature}><Save/>{saving?"Salvando...":"Assinar e salvar"}</button></div></section></div>}
 </main>
}
