"use client";
import {useEffect,useRef,useState} from "react";
import Link from "next/link";
import {ArrowLeft,Expand,KeyRound,Monitor,PenLine,RefreshCw,RotateCcw,Save} from "lucide-react";
import {supabase} from "@/lib/supabase";
type Slot={id:string;slot_number:number;status:string}; type Ev={key_slot_id:string;event_type:string;holder_name:string;mission:string|null;occurred_at:string};
export default function Claviculario(){
 const[slots,setSlots]=useState<Slot[]>([]),[events,setEvents]=useState<Ev[]>([]),[selected,setSelected]=useState<Slot|null>(null),[monitor,setMonitor]=useState(false);
 const[mission,setMission]=useState(""),[destination,setDestination]=useState(""),[external,setExternal]=useState(""),[message,setMessage]=useState(""),[saving,setSaving]=useState(false);
 const canvas=useRef<HTMLCanvasElement>(null),drawing=useRef(false);
 async function load(){const[{data:s},{data:e}]=await Promise.all([supabase.from("key_slots").select("*").eq("active",true).order("slot_number"),supabase.from("key_events").select("key_slot_id,event_type,holder_name,mission,occurred_at").order("occurred_at",{ascending:false}).limit(200)]);setSlots(s||[]);setEvents(e||[])}
 useEffect(()=>{load();const c=supabase.channel("keys").on("postgres_changes",{event:"*",schema:"public",table:"key_events"},load).subscribe();return()=>{supabase.removeChannel(c)}},[]);
 const latest=(id:string)=>events.find(e=>e.key_slot_id===id),out=(id:string)=>["checkout","transfer"].includes(latest(id)?.event_type||"");
 function pos(e:React.PointerEvent<HTMLCanvasElement>){const c=canvas.current!,r=c.getBoundingClientRect();return{x:(e.clientX-r.left)*c.width/r.width,y:(e.clientY-r.top)*c.height/r.height}}
 function start(e:React.PointerEvent<HTMLCanvasElement>){drawing.current=true;const p=pos(e),x=canvas.current!.getContext("2d")!;x.beginPath();x.moveTo(p.x,p.y);canvas.current!.setPointerCapture(e.pointerId)}
 function draw(e:React.PointerEvent<HTMLCanvasElement>){if(!drawing.current)return;const p=pos(e),x=canvas.current!.getContext("2d")!;x.lineWidth=3;x.lineCap="round";x.strokeStyle="#071f3c";x.lineTo(p.x,p.y);x.stroke()}
 function clear(){canvas.current?.getContext("2d")?.clearRect(0,0,700,220)}
 async function save(){if(!selected||!mission.trim()){setMessage("Informe a missão.");return}setSaving(true);const{data:{user}}=await supabase.auth.getUser();if(!user){setMessage("Sessão expirada.");setSaving(false);return}
  const{data:p}=await supabase.from("profiles").select("full_name,rank,military_id").eq("id",user.id).single();const blob=await new Promise<Blob|null>(r=>canvas.current?.toBlob(r,"image/webp",.55));if(!blob){setMessage("Faça a assinatura.");setSaving(false);return}
  const buffer=await blob.arrayBuffer(),hash=Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",buffer))).map(b=>b.toString(16).padStart(2,"0")).join(""),clientId=crypto.randomUUID(),path=user.id+"/"+new Date().toISOString().slice(0,10)+"/"+clientId+".webp";
  const up=await supabase.storage.from("key-signatures").upload(path,blob,{contentType:"image/webp"});if(up.error){setMessage("Erro ao salvar assinatura.");setSaving(false);return}const type=out(selected.id)?"return":"checkout";
  const{error}=await supabase.from("key_events").insert({key_slot_id:selected.id,event_type:type,holder_user_id:user.id,holder_name:p?.full_name||user.email||"Usuário",holder_rank:p?.rank,holder_military_id:p?.military_id,mission,destination,notes:external?"Viatura externa: "+external:null,signature_path:path,signature_sha256:hash,witnessed_by:user.id,client_event_id:clientId});
  if(error){setMessage(error.message);setSaving(false);return}await supabase.from("key_slots").update({status:type==="checkout"?"checked_out":"available"}).eq("id",selected.id);setMessage(type==="checkout"?"Retirada assinada.":"Devolução assinada.");setSelected(null);setMission("");clear();await load();setSaving(false)}
 return <main className={monitor?"key-page monitor-mode":"key-page"}><header className="key-header"><div><Link href="/"><ArrowLeft/></Link><img src="/ssv-logo-transparent.png" alt="SSV"/><span><b>Claviculário Digital</b><small>Retirada e devolução de chaves</small></span></div><div className="key-actions"><button onClick={load}><RefreshCw/>Atualizar</button><button onClick={()=>setMonitor(!monitor)}><Monitor/>Monitor</button><button onClick={()=>document.documentElement.requestFullscreen?.()}><Expand/>Tela cheia</button></div></header>
 <section className="key-summary"><div><b>{slots.length}</b><small>Posições</small></div><div><b>{slots.filter(s=>!out(s.id)).length}</b><small>Disponíveis</small></div><div><b>{slots.filter(s=>out(s.id)).length}</b><small>Retiradas</small></div></section>
 <section className="key-grid">{slots.map(s=>{const e=latest(s.id),busy=out(s.id);return <button key={s.id} className={busy?"key-slot busy":"key-slot"} onClick={()=>!monitor&&setSelected(s)}><strong>{s.slot_number}</strong><KeyRound/><b>{busy?"RETIRADA":"DISPONÍVEL"}</b>{e&&<><small>{e.holder_name}</small><em>{e.mission||"Sem missão"}</em><time>{new Date(e.occurred_at).toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"})}</time></>}</button>})}</section>
 {selected&&<div className="key-modal-bg"><section className="key-modal"><div className="key-modal-title"><strong>{selected.slot_number}</strong><div><small>{out(selected.id)?"DEVOLUÇÃO":"RETIRADA"}</small><h2>Posição {selected.slot_number}</h2></div></div><label>Viatura externa/temporária<input value={external} onChange={e=>setExternal(e.target.value)} placeholder="Ex.: Prefeitura — 10DP174"/></label><label>Missão<input value={mission} onChange={e=>setMission(e.target.value)} required/></label><label>Destino<input value={destination} onChange={e=>setDestination(e.target.value)}/></label><label className="signature-label"><span><PenLine/>Assine com o dedo</span><canvas ref={canvas} width="700" height="220" onPointerDown={start} onPointerMove={draw} onPointerUp={()=>drawing.current=false}/><button onClick={clear}><RotateCcw/>Limpar</button></label>{message&&<p>{message}</p>}<div className="key-modal-actions"><button onClick={()=>setSelected(null)}>Cancelar</button><button className="key-save" onClick={save} disabled={saving}><Save/>{saving?"Salvando...":"Assinar e salvar"}</button></div></section></div>}</main>
}
