"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {LogIn} from "lucide-react";
import {createClient} from "@/lib/supabase/client";

export default function LoginPage(){
 const[email,setEmail]=useState(""),[password,setPassword]=useState(""),[message,setMessage]=useState(""),[loading,setLoading]=useState(false),[emailLoading,setEmailLoading]=useState(false);
 useEffect(()=>{if(new URLSearchParams(window.location.search).get("error")==="oauth")setMessage("Não foi possível concluir o login com Google. Tente novamente.")},[]);
 async function passwordLogin(e:React.FormEvent){e.preventDefault();setLoading(true);setMessage("");try{const{error}=await createClient().auth.signInWithPassword({email,password});if(error)throw error;setMessage("Acesso realizado. Redirecionando...");window.location.href="/"}catch{setMessage("E-mail ou senha inválidos.");setLoading(false)}}
 async function googleLogin(){setLoading(true);setMessage("");try{const{data,error}=await createClient().auth.signInWithOAuth({provider:"google",options:{redirectTo:`${window.location.origin}/auth/callback?next=/`}});if(error)throw error;if(!data.url)throw new Error("URL de autenticação não recebida");window.location.assign(data.url)}catch(error){setMessage(error instanceof Error?`Não foi possível iniciar o login Google: ${error.message}`:"Não foi possível iniciar o login Google.");setLoading(false)}}
 async function emailLinkLogin(){if(!email.trim()){setMessage("Informe um e-mail válido para receber o acesso.");return}setEmailLoading(true);setMessage("");try{const{error}=await createClient().auth.signInWithOtp({email:email.trim(),options:{emailRedirectTo:`${window.location.origin}/auth/callback?next=/`,shouldCreateUser:true,data:{registration_type:"driver_email_access"}}});if(error)throw error;setMessage("Enviamos um link de acesso para o seu e-mail. Abra a mensagem neste dispositivo para continuar.")}catch(error){setMessage(portugueseEmailError(error instanceof Error?error.message:undefined))}finally{setEmailLoading(false)}}
 return <main className="auth-page"><section className="auth-brand"><div className="auth-logo"><img src="/ssv-logo-transparent.png" alt="Logo SSV"/></div><b>SSV</b><h1>Sistema de Supervisão de Viaturas</h1><p>Controle seguro de viaturas, movimentações, checklists e manutenção.</p></section><section className="auth-card"><div><small>ACESSO AO SISTEMA</small><h2>Entrar no SSV</h2><p>Motorista: use o Google ou receba um link no seu e-mail. Contas novas ficam aguardando aprovação.</p></div><button className="google" onClick={googleLogin} disabled={loading||emailLoading}><span>G</span> Entrar com Google</button><div className="divider">ou</div><form onSubmit={passwordLogin}><label>E-mail<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required placeholder="nome@fab.mil.br"/></label><button type="button" className="email-link-login" onClick={()=>void emailLinkLogin()} disabled={loading||emailLoading}>{emailLoading?"Enviando link...":"Receber link de acesso"}</button><div className="divider">ou entre com senha</div><label>Senha<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required placeholder="Sua senha"/></label>{message&&<p className="form-message" role="alert">{message}</p>}<button className="auth-submit" disabled={loading||emailLoading}><LogIn/> {loading?"Aguarde...":"Entrar com senha"}</button></form><p className="auth-link">Sargento de Dia sem cadastro? <Link href="/cadastro">Solicitar acesso</Link></p></section></main>
}

function portugueseEmailError(message?:string){const value=message?.toLowerCase()??"";if(value.includes("invalid")&&value.includes("email"))return"Informe um e-mail válido.";if(value.includes("rate")||value.includes("too many"))return"Muitas tentativas em pouco tempo. Aguarde alguns minutos e tente novamente.";return"Não foi possível enviar o link de acesso. Confira o e-mail e tente novamente."}
